name: Aggiornamento Lista Fantacalcio 2026

on:
  schedule:
    - cron: '0 4 * * *' # Ogni giorno alle 04:00
  workflow_dispatch: # Permette di lanciarlo manualmente da GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Esegui aggiornamento giocatori
        run: python update_data.py

      - name: Commit e Push dei dati aggiornati
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add players.json
          git commit -m "Auto-update listone calciatori 2026" || exit 0
          git push
